name: Deploy application to production environment
on:
  push:
    branches: [ "dev", "workflow-cd" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to AlwaysData
        uses: appleboy/ssh-action@v1.2.4
        with:
          host: ssh-energydash.alwaysdata.net
          username: ${{ secrets.ALWAYSDATA_USERNAME }}
          password: ${{ secrets.ALWAYSDATA_PASSWORD }}
          port: 22
          script: |
            cd /www/
            composer install --no-dev --optimize-autoloader
            npm ci --production
            git pull origin main