name: PHP Composer

on:
  push:
    branches: [ "dev", "workflow-ci-cd" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Create .env file
        run: |
          {
            echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}"
            echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}"
            echo "DATABASE_USER=${{ secrets.DATABASE_USER }}"
            echo 'DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}'
            echo "SMTP_HOST=${{ secrets.SMTP_HOST }}"
            echo "SMTP_PORT=${{ secrets.SMTP_PORT }}"
            echo "SMTP_USER=${{ secrets.SMTP_USER }}"
            echo 'SMTP_PASS=${{ secrets.SMTP_PASS }}'
            echo "SMTP_FROM=${{ secrets.SMTP_FROM }}"
            echo 'SMTP_FROM_NAME=${{ secrets.SMTP_FROM_NAME }}'
            echo "APP_ENV=testing"
            echo "APP_DEBUG=true"
          } > .env

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit tests